### PR TITLE
Testing for cross platform

### PR DESCRIPTION
**Pull request by brucek**
This should fix the problem with open on both Windows and *nix (though I don't have environments handy here to test on)

As far as the other issue, I assume this command fails on the command line?

```sh
babel-node -r node_modules/.bin/isparta cover --include '**/*js' node_modules/.bin/_mocha -- --opts config/mocha.opts
```

I got that from either [here](https://onsen.io/blog/mocha-chaijs-unit-test-coverage-es6/) or [here](https://github.com/douglasduteil/isparta/issues/47) I think...  Maybe we need to use a separate task if you can't figure it out on Windows so at least there is a task that works?

### CODE REVIEW

**Comment by brucek** [comment]
although I hope `start` exists in Git bash...  I assume you can't be running Cygwin or CMD.exe, right?

**Comment by Kflash** [comment]
@brucek I used Git bash yes, and not working there. If I change to CMD it works.

**Comment by brucek** [comment]
OK, I just set up a VirtualBox instance with Git Bash and I do see the start command at `/usr/bin/start`, and it opens up the browser for me (although admittedly I haven't yet tried with npm, I'll work on that next).

1. Do you have `/usr/bin/start`?
2. Is `/usr/bin` on your $PATH?  Try `echo $PATH`

**Comment by Kflash** [comment]
I'm on Windows 10 atm and there is nothing like that. `C:\...`

**Comment by brucek** [comment]
Hmm, the version I have is Win7.  Can you give me the output of running `uname -s` in Git Bash?  I get `MINGW32` in Win7, for instance

**Comment by Kflash** [comment]
`MSYS_NT-10.0-WOW` Git Bash seems to be integrated with powershell

**Comment by brucek** [comment]
Does [this](http://superuser.com/questions/246825/open-file-from-the-command-line-on-windows) work for you?  Just the filename by itself, or the `powershell -c` version?  I can only get the `powershell -c` one to work for me...

**Comment by Kflash** [comment]
This works yes

**Comment by brucek** [comment]
OK, hopefully my last push to master works

**Comment by Kflash** [comment]
```
/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell
coverage/Phantom*/index.html : The term 'coverage/Phantom*/index.html' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ coverage/Phantom*/index.html
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (coverage/Phantom*/index.html:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

which: no xdg-open in (/c/Users/track/AppData/Roaming/npm/node_modules/npm/bin/node-gyp-bin:/c/xampp4/htdocs/trolly/node_modules/.bin:/c/Program Files (x86)/nodejs:/cmd:/usr/bin:/usr/share/git-tfs:/c/Users/track/AppData/Local/Apps/2.0/44DQOH7B.XYB/88NXK56Z.GDV/gith..tion_317444273a93ac29_0003.0000_d92b04e95b5b9794:/c/Users/track/AppData/Local/GitHub/lfs-amd64_1.1.0:/c/WINDOWS/Microsoft.NET/Framework/v4.0.30319:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/nodejs:/c/Users/track/AppData/Roaming/npm)
which: no open in (/c/Users/track/AppData/Roaming/npm/node_modules/npm/bin/node-gyp-bin:/c/xampp4/htdocs/trolly/node_modules/.bin:/c/Program Files (x86)/nodejs:/cmd:/usr/bin:/usr/share/git-tfs:/c/Users/track/AppData/Local/Apps/2.0/44DQOH7B.XYB/88NXK56Z.GDV/gith..tion_317444273a93ac29_0003.0000_d92b04e95b5b9794:/c/Users/track/AppData/Local/GitHub/lfs-amd64_1.1.0:/c/WINDOWS/Microsoft.NET/Framework/v4.0.30319:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/c/Program Files (x86)/nodejs:/c/Users/track/AppData/Roaming/npm)

```

**Pull request merged**
