### PR TITLE
Running with Sinon and babel-plugin-rewire

### PR DESCRIPTION
**Pull request by brucek**
See if this looks useful...  I basically had some problems getting sinon working and figured I would set up rewire while I'm at it - I added some code & tests demonstrating using both of those as well.

### CODE REVIEW

**Comment by Kflash** [comment]
@brucek Seems like there are some conflicts. Btw. you have write access to the repo now, so you don't need to send PR.

**Comment by Kflash** [comment]
Could you update the readme regarding this? Make a new section for rewire etc?

**Comment by Kflash** [comment]
@brucek I'm merging this, and then try to work on the test to fix the coverage. Meanwhile I need to update the readme

**Comment by brucek** [comment]
Oh yeah, I did notice you gave me commit access as well, thank you.  As long as you're OK with me pushing to master I'll just do that :-)

**Comment by Kflash** [comment]
It's all fine with me. That's the reason you got access :)

**Comment by Kflash** [comment]
@brucek I tried to port the rewire implementation over to my other workflow as well - boily. Everything works just fine except one of the tests fail with Karma. Almost the same setup for Karma so dunno what's wrong. Any ideas?

**Comment by brucek** [comment]
Huh, not sure...  I just ran your boily tests locally here (on OSX from commit https://github.com/Kflash/boily/commit/c677690f58588ca9bb19b3434b01e64e155cd458) and everything I can run (test, karma:phantom, karma:chrome, karma:firefox) all 100% pass.  Maybe it's something Windows-related?  Or IE?

**Comment by Kflash** [comment]
You need to remove the // before the last rewire test. I commented out one.
The Strange thinghere is that this test only fails with karma.  If you type

`npm run browser`

And open port 8080 no test fails.

**Comment by brucek** [comment]
it was your .babelrc for some reason

**Pull request merged**
