### PR TITLE
Mocha es6 coverage

### PR DESCRIPTION
**Pull request by brucek**
Running isparta for code coverage on server tests under mocha cli

### CODE REVIEW

**Comment by brucek** [comment]
Also helps as sourcemaps work with mocha cli, making #19 less terrible

**Comment by Kflash** [comment]
@brucek `open` is not working on Windows environments. Any solution?

**Comment by Kflash** [comment]
@brucek  And running server tests in a Windows environment gives me this:

```
C:\xampp4\htdocs\trolly\node_modules\.bin\isparta:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xampp4\htdocs\trolly\node_modules\babel-register\lib\node.js:134:7)
    at Module.load (module.js:357:32)
```

**Comment by brucek** [comment]
Oops - sorry I missed this until now but I guess adding cross-env solved it?

**Comment by Kflash** [comment]
No problem. I though cross-env should solve the issue, but it's still there. Both for server tests and coverage. And `open` is only for Mac, not Windows environment.

I haven't had time to dig into this, but if you have some time.., maybe you know whats going on?

**Pull request merged**
